Ax gaze estimator
kyoto-kaira/eye-track-cursor pull request #1
Opened 2024-10-07 14:38 UTC by syarasyoujyu

@matsuda-tkm 
完了しました！

2024-10-07 14:40 UTC, syarasyoujyu commented
コンフリクトが怖くてeye_trackerブランチにはPushせず、新しいブランチ上でPushしました

2024-10-07 15:14 UTC, matsuda-tkm commented
- `eye-track-cursor/ax_gaze_estimator`ではなく`eye-track-cursor/backend`に改名して欲しいです！
- データ系（サンプル画像、学習済みモデル、カメラパラメータなど）はdata/ディレクトリにまとめる（data/の中にさらにディレクトリ作成してわかりやすく整理）
- AxGazeEstimationのコードをカスタマイズするのではなくて、AxGazeEstimationのコード内のクラスや関数を呼び出す形で使うようにする。（つまりライブラリのように使う）
```python
from ax_gaze_estimation import GazeEstimator

img = ....

estimator = GazeEstimator()
pred = estimator.predict(img)
...
```
- 自分で書いた関数にはdocstringと型ヒントをつける（下記例）。RaisesとかExampleはなくてもよいですが、ParametersとReturnは書いて欲しいです！
```python
from typing import List, Union

def calculate_average(values: List[Union[int, float]]) -> float:
    """
    数値のリストの平均を計算する。

    Parameters
    ----------
    values : List[Union[int, float]]
        平均を計算したい対象のリスト

    Returns
    -------
    float
        入力された数値のリストの平均値

    Raises
    ------
    ValueError
        リストが空の場合、またはリストの要素が数値でない場合

    Examples
    --------
    >>> calculate_average([1, 2, 3, 4, 5])
    3.0
    >>> calculate_average([1.5, 2.5, 3.5])
    2.5
    """
    if not values:
        raise ValueError("リストが空です。平均を計算できません。")

    if not all(isinstance(x, (int, float)) for x in values):
        raise ValueError("リストには数値のみ含める必要があります。")

    return sum(values) / len(values)
```

2024-10-08 06:01 UTC, syarasyoujyu commented
@matsuda-tkm 
修正完了しました！

2024-10-08 06:42 UTC, matsuda-tkm reviewed
コメントしました！

2024-10-08 06:42 UTC, matsuda-tkm commented on backend/eye_points_estimation.py
> +def get_facial_landmarks(image:np.ndarray)->Tuple[np.ndarray,np.ndarray]:
細かくてすみませんが、リーダブルなコードにするためのフィードバックです！

- Pythonコーディング規約PEP8を意識した書き方にすると読みやすくなります！
    - 関数と関数の間は2行空ける
    - カンマ`,`やコロン`:`の後は半角1スペースおく
    - （他の箇所も確認してくださいね😉）
- 定数は大文字で、冒頭の方にまとめておくといいです！
- コメントアウトの書き方
    - `#`と文章の間は半角1スペース空ける
    - コードの横に書く場合は、コードと`#`の間は半角2スペース空ける

```suggestion

PREDICTOR_PATH = "data/params/shape_predictor_68_face_landmarks.dat"  
CAMERA_CALIB_PATH = "data/params/cameraCalib.xml"
fx, fy, cx, cy = 960, 960, 640, 360  # カメラの焦点距離（fx, fy）と中心点（cx, cy）

# 顔検出モデルと顔の特徴点予測モデルを取得
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(PREDICTOR_PATH)

# カメラ行列を設定
camera_matrix = np.array([
    [fx,  0,  cx],
    [ 0, fy,  cy],
    [ 0,  0,   1]
]).astype(np.float64)

# カメラの歪み係数を読み込む
fid = cv2.FileStorage(CAMERA_CALIB_PATH, cv2.FileStorage_READ)
camera_distortion = fid.getNode("cam_distortion").mat()


def get_facial_landmarks(image: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
```

2024-10-08 06:42 UTC, matsuda-tkm commented on backend/eye_points_estimation.py
> +    _summary_
不要

2024-10-08 06:42 UTC, matsuda-tkm commented on backend/eye_points_estimation.py
> +def estimateHeadPose(landmarks:np.ndarray, face_model:np.ndarray, iterate=True):
- `face_model`という名前だと、モデルを入れるのかな？と思っちゃうので別の名前にしたいです
- Pythonではあまりキャメルケースは使わないので関数名は`estimate_head_pose`がいいかな？
    - 参考：https://qiita.com/2Gken1029/items/c1733e8780e2b527ae00

2024-10-08 06:42 UTC, matsuda-tkm commented on backend/eye_points_estimation.py
> +        distortion: カメラの歪み係数
残っちゃってるので消してください！

2024-10-08 06:42 UTC, matsuda-tkm commented on backend/eye_points_estimation.py
> +        gc: 視線
残っちゃってるので消してください！

2024-10-08 06:42 UTC, matsuda-tkm commented on backend/eye_points_estimation.py
> +    filepath = os.path.join(path)
path: strなら、os.path.joinをする意味がない気がするのですがどうでしょう？

2024-10-08 06:42 UTC, matsuda-tkm commented on backend/eye_points_estimation.py
> +    face = np.loadtxt('data/params/faceModelGeneric.txt')
`'data/params/faceModelGeneric.txt'`を定数として先頭で定義しましょうか

2024-10-08 06:42 UTC, matsuda-tkm commented on README.md
- Pythonのバージョンを記述してください
- backendの関数を使って、フロントエンドで視線位置を表示することになります。ですので、フロントエンドを開発する方が「どの関数をどのように使えばどういう返り値が得られるのか？」がわかるように書いて欲しいです！

2024-10-08 14:42 UTC, syarasyoujyu commented
@matsuda-tkm 
修正できました！

2024-10-08 15:12 UTC, matsuda-tkm commented on README.md
> +4\. backend/ax_gaze_estimation.pyのmain関数を実行する（引数は不要）と、{~(ファイル名:str):~~(スクリーン座標系における視点座標:np.ndarray)}のdict型を返してくれる
動画処理するのでこの仕様はキツイですね...。（動画のフレームを逐一保存することになるのでI/O処理がかなりボトルネックになる）
イメージ伝わりきってなかったのでもう少し具体化しますね！

### フロント側の操作イメージ
OpenCVのcv2.VideoCaptureでフレームを取得して、np.ndarrayとしてAIに渡す

### バックエンドで用意する関数
- Calibration時に使用する関数
    - Parameters：画像(np.ndarray)
    - Returns：Calibration結果(推論時に必要な情報を詰め込んだdict(listでもなんでも良い))
- 推論に使用する関数
    - Parameters：画像(np.ndarray)・Calibration結果(上のものと同じ)・画面の縦横長さ(Tuple[int, int])
    - Returns：画面位置(Tuple[int, int])
- [あると良い] 視線描画関数
    - Parameters：画像(np.ndarray)
    - Returns：視線ベクトルを書き込んだ画像(np.ndarray)

### 注
- それぞれの関数内に処理をダラダラ書くとよみづらいので、まとめられる処理は別の関数として切り出して、読みやすくなるようにしましょうね！
- README.mdに書いて欲しいことは、上記3つの関数の一覧および引数・返り値の説明です！
- 上記のParametersはこの情報があれば推定可能だろう、と考えて書きましたが万一漏れがあれば追加してください。（ただし余分な引数は増やさない）

2024-10-09 02:28 UTC, syarasyoujyu commented
@matsuda-tkm 
修正終わりました！

2024-10-10 06:59 UTC, syarasyoujyu commented
@matsuda-tkm 
外部から重みとモデルをDLしていたことを忘れておりました。
申し訳ないです

2024-10-10 07:37 UTC, matsuda-tkm commented
@syarasyoujyu 
ありがとうございます！
いまpushしていただいたデータを移動してもらってもいいですか？
データ関連なので、rootではなくbackend/dataの中に入れたいです。

P.S. レビューする時間取れておらず申し訳ないです、遅くとも土日にはレビューします...。

2024-10-11 08:20 UTC, matsuda-tkm requested changes
動かしてみましたが全然動かないので、
- テストコードを書く
- テストが通るまで修正する
- PR再依頼
でお願いします！あと一部コメントしているのでついでに対応お願いします。

テストコードというのは、README記載の3つの関数の動作を確認するコードです。`backend/ax_gaze_estimation.py`の末尾に書いてあるような感じでbackend/tests.pyなど別ファイルに書いてください。「カメラ画像取り込んで〜」とかはいらないので、サンプル画像（center.jpgとか？）に対して推論行う感じでいいと思います。

2024-10-11 08:20 UTC, matsuda-tkm commented on backend/ax_gaze_estimation.py
> +        print("gazes_vec", gazes_vec)
printではなく[logging](https://qiita.com/nano-sudo/items/60a219f932245eba82a1)使ってほしいです！
（他も同様）

2024-10-11 08:20 UTC, matsuda-tkm commented on backend/ax_gaze_estimation.py
> +        )
[MUST]
drawという関数が見つからないです

2024-10-11 08:20 UTC, matsuda-tkm commented on backend/ax_gaze_estimation.py
> +    dst_points = np.float32(screen_positions)
[nits]
あまりこういう書き方はしないかも...
`np.array(gaze_points, dtype=np.float32)`が一般的な書き方です

2024-10-11 08:20 UTC, matsuda-tkm commented on backend/eye_points_estimation.py
> +GAZE_REMOTE_PATH = f'https://storage.googleapis.com/ailia-models/ax_gaze_estimation/'
[nits]
f不要

2024-10-11 08:20 UTC, matsuda-tkm commented on backend/ax_gaze_estimation.py
> +        raise ValueError("キャリブレーションが実行されていません。")
[MUST]
キャリブレーション結果をestimator_data["calibration_result"]に入れる方針と、`M`で管理する方針が混ざっているようなので解消してください（この例外処理を消して、estimator_data["calibration_result"]を消せばいいと思います）。
現状だとキャリブレーション行ってもこの例外に引っ掛かります。

2024-10-12 01:50 UTC, syarasyoujyu commented
@matsuda-tkm 
修正出来ました！
何度もPRして申し訳ないです....

2024-10-12 03:30 UTC, matsuda-tkm commented on backend/ax_gaze_estimation.py
> +import ax_gaze_estimation_utils as gut
- 相対インポートにしてください。frontendから呼び出す際にimportエラーになります。
- また、import文で横に長くなる時はカッコでくくって改行するとみやすくなります！

```suggestion
from .eye_points_estimation import (
    calculate_gaze_point,
    initialize_gaze_estimator,
    fetch_eye_locations_from_image
)
from . import ax_gaze_estimation_utils as gut
```

2024-10-12 03:30 UTC, matsuda-tkm commented on backend/ax_gaze_estimation_utils.py
> +from utils.math_utils import softmax
- 相対インポートにしてください。frontendから呼び出す際にimportエラーになります。

```suggestion
from .utils.math_utils import softmax
```

2024-10-12 04:22 UTC, matsuda-tkm commented
ちなみに↑の相対インポートにした場合、普通に
```bash
python backend/ax_gaze_estimation.py
```
とすると通りません。そこで以下のようなコマンドにして、カレントディレクトリをPYTHONPATHに設定することでちゃんとパスが通ります。
```bash
python -m backend.ax_gaze_estimation
```

2024-10-12 05:48 UTC, syarasyoujyu commented
@matsuda-tkm 
修正できました！

2024-10-12 06:20 UTC, matsuda-tkm approved these changes
ありがとうございます！
いろいろな要求に粘り強く対応していただき、大変助かりました！

mainにマージしてください！

2024-10-12 06:49 UTC, merged